name: Build APK - Controle de Gastos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependências de build e limpar cache
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3
          npm ci
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v2

      - name: Sincronizar Capacitor com o Android
        run: |
          npx cap sync android

      - name: Construir APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Fazer upload do APK como artefato
        uses: actions/upload-artifact@v3
        with:
          name: controle-de-gastos-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
