name: Build APK - Controle de Gastos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3
          npm ci
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.1.8937393'
          cmake-version: '3.22.1'

      - name: Configurar variáveis de ambiente Android
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Sincronizar Capacitor
        run: |
          npx cap sync android

      - name: Build APK Debug
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
